"""Read-only extraction of T32_PI05_Final_Report.docx to Markdown.

This exists because the review pipeline needs plain text to work on and this
machine has neither pandoc nor python-docx. It uses the standard library only.

The docx is never opened for writing. Nothing here modifies the report.

Paragraph-index convention
--------------------------
Indices are the position of each ``<w:p>`` element in document order under
``<w:body>``, counting from 0 and including paragraphs nested inside tables.
Every finding in the review reports is anchored to one of these indices, so the
convention must not change: re-running this script must reproduce the same
numbering. Use ``--index N`` to print a single paragraph and confirm an anchor.

Usage
-----
    python extract_report.py                # write report-extracted.md alongside
    python extract_report.py --index 885    # print one paragraph, with context
    python extract_report.py --equations    # dump the OMML equation inventory
    python extract_report.py --citations    # dump in-text citations found
"""

from __future__ import annotations

import argparse
import re
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

W = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"
M = "{http://schemas.openxmlformats.org/officeDocument/2006/math}"
A = "{http://schemas.openxmlformats.org/drawingml/2006/main}"

HERE = Path(__file__).resolve().parent
DOCX = HERE.parents[2] / "T32_PI05_Final_Report.docx"  # .../src/
OUT = HERE / "report-extracted.md"

# Author-date citations: "(Smith, 2020)", "Smith et al. (2020)", "(Smith & Lee, 2020; Ho, 2019)".
CITATION_RE = re.compile(
    r"\(([^()]*?\d{4}[a-z]?|[^()]*?n\.d\.)[^()]*?\)"
    r"|([A-Z][A-Za-zÀ-ɏ'-]+(?:\s+(?:et\s+al\.|&\s+[A-Z][A-Za-z'-]+))?)"
    r"\s*\((\d{4}[a-z]?|n\.d\.)\)"
)


def load_body(path: Path) -> ET.Element:
    with zipfile.ZipFile(path) as z:
        root = ET.fromstring(z.read("word/document.xml"))
    body = root.find(W + "body")
    if body is None:
        raise SystemExit("no <w:body> in document.xml")
    return body


def para_style(p: ET.Element) -> str:
    style = p.find(W + "pPr/" + W + "pStyle")
    return style.get(W + "val", "") if style is not None else ""


def para_text(p: ET.Element) -> str:
    """Flattened text, with OMML equations inlined as $...$ placeholders.

    Equation structure (fractions, sub/superscripts) is lost -- only the symbol
    run survives. That is enough to inventory notation, not to typeset it.
    """
    out: list[str] = []
    for node in p.iter():
        if node.tag == W + "t":
            out.append(node.text or "")
        elif node.tag == M + "oMath":
            sym = "".join(t.text or "" for t in node.iter(M + "t"))
            out.append(f" $`{sym}`$ " if sym.strip() else " $`?`$ ")
        elif node.tag == W + "tab":
            out.append("\t")
        elif node.tag == W + "br":
            out.append("\n")
    # w:t inside m:oMath would double-count; drop the duplication.
    text = "".join(out)
    return re.sub(r"[ \t]+", " ", text).strip()


def is_in_math(p: ET.Element) -> bool:
    return p.find(".//" + M + "oMath") is not None


def paragraphs(body: ET.Element) -> list[tuple[int, str, str]]:
    rows = []
    for i, p in enumerate(body.iter(W + "p")):
        rows.append((i, para_style(p), para_text(p)))
    return rows


def n_images(p: ET.Element) -> int:
    return len(list(p.iter(A + "blip")))


def to_markdown(body: ET.Element) -> str:
    lines = [
        "# T32_PI05_Final_Report — verbatim extraction",
        "",
        "> Generated by `extract_report.py` from `src/T32_PI05_Final_Report.docx`.",
        "> This is a **read-only derivative**, not a revised draft. Text is reproduced",
        "> as-is, including its errors — those are the subject of the review.",
        "> `[p123]` markers are paragraph indices (see the script docstring); every",
        "> review finding anchors to one. Equations appear as `` $`symbols`$ `` with",
        "> their structure flattened.",
        "",
        "---",
        "",
    ]
    for i, p in enumerate(body.iter(W + "p")):
        style = para_style(p)
        text = para_text(p)
        imgs = n_images(p)
        if imgs and not text:
            lines.append(f"[p{i}] *({imgs} embedded image{'s' if imgs > 1 else ''})*")
            lines.append("")
            continue
        if not text:
            continue
        level = 0
        m = re.match(r"[Hh]eading(\d)", style)
        if m:
            level = int(m.group(1))
        elif style in ("Title", "Subtitle"):
            level = 1
        if level:
            lines.append(f"{'#' * min(level + 1, 6)} [p{i}] {text}")
        elif style.lower().startswith("list"):
            lines.append(f"- [p{i}] {text}")
        else:
            lines.append(f"[p{i}] {text}")
        lines.append("")
    return "\n".join(lines) + "\n"


def dump_equations(body: ET.Element) -> None:
    n = 0
    for i, p in enumerate(body.iter(W + "p")):
        for eq in p.iter(M + "oMath"):
            sym = "".join(t.text or "" for t in eq.iter(M + "t"))
            print(f"p{i}\t{sym}")
            n += 1
    print(f"\n# {n} OMML equations", file=sys.stderr)


def dump_citations(body: ET.Element) -> None:
    seen: dict[str, list[int]] = {}
    for i, _, text in paragraphs(body):
        for match in CITATION_RE.finditer(text):
            cite = match.group(0).strip()
            seen.setdefault(cite, []).append(i)
    for cite, paras in sorted(seen.items(), key=lambda kv: kv[1][0]):
        locs = ", ".join(f"p{p}" for p in paras[:8])
        print(f"{len(paras):3d}x  {cite:60s} {locs}")
    print(f"\n# {len(seen)} distinct in-text citation strings", file=sys.stderr)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--index", type=int, help="print one paragraph with context")
    ap.add_argument("--equations", action="store_true", help="dump OMML inventory")
    ap.add_argument("--citations", action="store_true", help="dump in-text citations")
    args = ap.parse_args()

    if not DOCX.exists():
        raise SystemExit(f"report not found: {DOCX}")
    body = load_body(DOCX)

    if args.equations:
        dump_equations(body)
        return
    if args.citations:
        dump_citations(body)
        return
    if args.index is not None:
        rows = paragraphs(body)
        lo, hi = max(0, args.index - 2), min(len(rows), args.index + 3)
        for i, style, text in rows[lo:hi]:
            marker = ">>" if i == args.index else "  "
            print(f"{marker} p{i} [{style or 'Body'}] {text}")
        return

    OUT.write_text(to_markdown(body), encoding="utf-8")
    rows = paragraphs(body)
    words = sum(len(t.split()) for _, _, t in rows)
    print(f"wrote {OUT}")
    print(f"  {len(rows)} paragraphs, ~{words} words")


if __name__ == "__main__":
    main()
